CREATE TABLE IF NOT EXISTS points (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  note TEXT,
status TEXT DEFAULT 'planowany',
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS photos (
  id SERIAL PRIMARY KEY,
  point_id INT REFERENCES points(id) ON DELETE CASCADE,
  url TEXT NOT NULL
);
